//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace naseNut.WebApi.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Batch
    {
        public int Id { get; set; }
        public string Batch1 { get; set; }
        public double Hectares { get; set; }
        public int FieldId { get; set; }
    
        public virtual Field Field { get; set; }
        public virtual Box Box { get; set; }
    }
}
