//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace naseNut.WebApi.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeApplied
    {
        public int Id { get; set; }
        public System.DateTime SyncStartTime { get; set; }
        public System.DateTime SyncEndTime { get; set; }
        public int UploadChangesTotal { get; set; }
        public int DownloadChangesTotal { get; set; }
        public string TableName { get; set; }
    }
}
