//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace naseNut.WebApi.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cylinder_Reception
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cylinder_Reception()
        {
            this.Humidities = new HashSet<Humidity>();
        }
    
        public int Id { get; set; }
        public bool Active { get; set; }
        public int ReceptionId { get; set; }
        public int CylinderId { get; set; }
    
        public virtual Cylinder Cylinder { get; set; }
        public virtual Reception Reception { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Humidity> Humidities { get; set; }
    }
}
