//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace naseNut.WebApi.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Grill()
        {
            this.Receptions = new HashSet<Reception>();
        }
    
        public int Id { get; set; }
        public System.DateTime DateCapture { get; set; }
        public int ReceptionId { get; set; }
        public int Size { get; set; }
        public int Sacks { get; set; }
        public double Kilos { get; set; }
        public int Quality { get; set; }
        public string Variety { get; set; }
        public string Producer { get; set; }
        public string FieldName { get; set; }
        public string Cylinder { get; set; }
        public int NutAmount { get; set; }
        public double SelectPercentage { get; set; }
        public double TotalPercentage { get; set; }
        public double Humidity { get; set; }
        public bool Status { get; set; }
    
        public virtual Sampling Sampling { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reception> Receptions { get; set; }
    }
}
