//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace naseNut.WebApi.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrillIssue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GrillIssue()
        {
            this.Grills = new HashSet<Grill>();
        }
    
        public int Id { get; set; }
        public System.DateTime DateCapture { get; set; }
        public string Truck { get; set; }
        public string Driver { get; set; }
        public string Box { get; set; }
        public int Remission { get; set; }
        public int HarvestSeasonId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grill> Grills { get; set; }
        public virtual HarvestSeason HarvestSeason { get; set; }
    }
}
