//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace naseNut.WebApi.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Grill()
        {
            this.Samplings = new HashSet<Sampling>();
            this.Receptions = new HashSet<Reception>();
        }
    
        public int Id { get; set; }
        public System.DateTime DateCapture { get; set; }
        public int ReceptionId { get; set; }
        public int Size { get; set; }
        public int Sacks { get; set; }
        public double Kilos { get; set; }
        public Nullable<int> GrillIssuesId { get; set; }
        public int Quality { get; set; }
        public string FieldName { get; set; }
        public bool Status { get; set; }
        public int ProducerId { get; set; }
        public int VarietyId { get; set; }
    
        public virtual GrillIssue GrillIssue { get; set; }
        public virtual Producer Producer { get; set; }
        public virtual Variety Variety { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sampling> Samplings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reception> Receptions { get; set; }
    }
}
