//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace naseNut.WebApi.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NaseNEntities : DbContext
    {
        public NaseNEntities()
            : base("name=NaseNEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Cylinder> Cylinder { get; set; }
        public virtual DbSet<Grill> Grill { get; set; }
        public virtual DbSet<Humidity> Humidity { get; set; }
        public virtual DbSet<Producer> Producer { get; set; }
        public virtual DbSet<Reception> Reception { get; set; }
        public virtual DbSet<Remission> Remission { get; set; }
        public virtual DbSet<Sampling> Sampling { get; set; }
    }
}
