//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace naseNut.WebApi.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NutType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NutType()
        {
            this.NutSizeProcessResults = new HashSet<NutSizeProcessResult>();
        }
    
        public int Id { get; set; }
        public byte NutType1 { get; set; }
        public Nullable<int> Sacks { get; set; }
        public Nullable<double> Kilos { get; set; }
        public Nullable<int> ReceptionEntryId { get; set; }
        public Nullable<int> SamplingId { get; set; }
    
        public virtual Sampling Sampling { get; set; }
        public virtual ReceptionEntry ReceptionEntry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NutSizeProcessResult> NutSizeProcessResults { get; set; }
    }
}
