//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace naseNut.WebApi.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reception
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reception()
        {
            this.Remissions = new HashSet<Remission>();
            this.Grills = new HashSet<Grill>();
        }
    
        public int Id { get; set; }
        public double ReceivedFromField { get; set; }
        public string CarRegistration { get; set; }
        public Nullable<double> HeatHoursDtrying { get; set; }
        public Nullable<double> HumidityPercent { get; set; }
        public string Observations { get; set; }
        public int GrillId { get; set; }
        public int Folio { get; set; }
        public int ReceptionEntryId { get; set; }
        public int FieldId { get; set; }
    
        public virtual ReceptionEntry ReceptionEntry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Remission> Remissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grill> Grills { get; set; }
        public virtual Field Field { get; set; }
    }
}
