//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace naseNut.WebApi.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remission
    {
        public int Id { get; set; }
        public string Cultivation { get; set; }
        public string Batch { get; set; }
        public double Quantity { get; set; }
        public string Butler { get; set; }
        public int TransportNumber { get; set; }
        public string Driver { get; set; }
        public string Elaborate { get; set; }
        public int ReceptionId { get; set; }
        public System.DateTime DateCapture { get; set; }
    
        public virtual Reception Reception { get; set; }
    }
}
