//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace naseNut.WebApi.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sampling
    {
        public int Id { get; set; }
        public System.DateTime DateCapture { get; set; }
        public double SampleWeight { get; set; }
        public double HumidityPercent { get; set; }
        public int WalnutNumber { get; set; }
        public double Performance { get; set; }
        public double TotalWeightOfEdibleNuts { get; set; }
    
        public virtual Grill Grill { get; set; }
    }
}
