//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace naseNut.WebApi.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TotalHumidityView
    {
        public int HumidityId { get; set; }
        public System.DateTime HumidityDateCapture { get; set; }
        public double HumidityPercent { get; set; }
        public int CylinderId { get; set; }
        public int ReceptionId { get; set; }
        public string Variety { get; set; }
        public double ReceivedFromField { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string ProducerName { get; set; }
        public string CylinderName { get; set; }
    }
}
